apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.image.repository }}
    tag: {{ .Values.image.tag }}
  name: {{ .Values.image.repository }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - port: {{ .Values.services.port }}
    protocol: {{ .Values.services.protocol }}
    targetPort: {{ .Values.services.targetPort }}
  selector:
    app: {{ .Values.image.repository }}
    tag: {{ .Values.image.tag }}
  type: {{ .Values.services.type }}